dataset_name: epic
train_split: ['training']
val_split: ['validation']
test_split: ['test']
dataset: {
  is_test: False,
  json_file: /data3/heyuping/epic100/epic_kitchens/annotations/epic_kitchens_100_action.json,
  # json_file: /home/heyuping/actionformer_release/epic_test_anno.json,
  feat_folder: /data3/heyuping/epic100/epic_kitchens/features,
  file_prefix: ~,
  file_ext: .npz,
  num_classes: 3806,
  input_dim: 2304,
  feat_stride: 16,
  num_frames: 32,
  default_fps: 30,
  trunc_thresh: 0.3,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
}
model: {
  regression_range: [[0, 4], [2, 8], [4, 16], [8, 32], [16, 64], [32, 10000]],
  fpn_type: identity,
  max_buffer_len_factor: 4.0,
  n_mha_win_size: 9,
}
opt: {
  learning_rate: 0.0001,
  epochs: 26,
  weight_decay: 0.05,
}
loader: {
  batch_size: 6,
}
train_cfg: {
  init_loss_norm: 250,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
}
test_cfg: {
  pre_nms_topk: 5000,
  max_seg_num: 2000,
  min_score: 0.001,
  nms_sigma : 2.0,
  multiclass_nms: True
}
output_folder: /data3/heyuping/epic100/ckpt/
